script

diff --git a/bin/concerto b/bin/concerto
--- a/bin/concerto
+++ b/bin/concerto
@@ -11,7 +11,6 @@ set -u -e
 concerto=$0
 
 client=${client:=redishub}
-client_authorized_certs=${client}_authorized_certs
 
 . bin/_${client}.sh
 . bin/_util.sh
@@ -108,7 +107,7 @@ c1deploy() { # id - copy generated cert files to $priv
   openssl x509 -text -in cert.pem | grep 'CN='
   headline "$priv $ ls"
   ls -lt
-  hint "$concerto ghadd $id"
+  hint "$concerto ghadd $id $defaultRole"
 }
 
 c0deploy() {
@@ -117,24 +116,15 @@ c0deploy() {
    c1deploy `cat $priv/latest.id`
 }
 
-c1genm() {
-   carg $# genm id
-   id=$1
-   echo "spec: 'concerto/manifest#0.1.0'"
-   echo "certs: ["
-   echo "  '${id}.cert.pem'"
-   echo "]"
-}
-
 c0ghcheck() {
    carg $# ghcheck
    if [ ! -d $repo ]
    then
       abort "Not found: $repo" "First try 'ghinit' or 'ghclone'"
    fi
-   if [ ! -f $repo/$client_authorized_certs.cson ]
+   if [ ! -f $repo/$client/manifest.json ]
    then
-      abort "Not found: $repo/$client_authorized_certs.cson" "First try 'ghinit' or 'ghclone'"
+      abort "Not found: $repo/$client/manifest.json" "First try 'ghinit' or 'ghclone'"
    fi
 }
 
@@ -142,46 +132,48 @@ c1gharchiveid() {
    carg $# gharchiveid id
    id="$1"
    c0ghcheck
-   cd $repo
-   [ ! -f $id.cert.pem ] && abortc "Not found: $repo/$id.cert.pem" "$concerto ghadd $id"
+   cd $repo/certs
+   [ ! -f $id.cert.pem ] && abortc "Not found: $repo/certs/$id.cert.pem" "$concerto ghadd $id"
    mv $id.cert.pem $archive/.
    headline "Moved $id.cert.pem to $archive"
    ls -lt | head
 }
 
-c1ghadd() {
-   carg $# ghadd id
-   id="$1"
+c2ghadd() {
+   carg $# ghadd id role
+   id=$1
+   role=$2
    c0ghcheck
    cd $repo
-   headline `pwd`
-   [ -f $id.cert.pem ] && abortc "Already exists: $id.cert.pem" "$concerto gharchiveid $id"
-   headline "Copying $id.cert.pem to repo: $repo"
-   cp $priv/tmp/$id.cert.pem $repo
-   sha1sum `ls -t *.pem`
-   if cat $repo/$client_authorized_certs.cson | grep -q "'$id.cert.pem'"
+   headline `pwd` ghadd $id $role
+   [ -f $priv/tmp/${id}.cert.pem ] || abort "Not found: $priv/tmp/${id}.cert.pem"
+   [ -f certs/$id.cert.pem ] && abortc "Already exists: $repo/certs/$id.cert.pem" "$concerto gharchiveid $id"
+   openssl x509 -text -in certs/${id}.cert.pem | grep 'CN='
+   headline "Copying $priv/tmp/$id.cert.pem to repo: $repo/certs"
+   cp $priv/tmp/$id.cert.pem $repo/certs
+   if cat $repo/$client/$role.txt | grep -q "^$id.cert.pem"
    then
-      warn "Manifest $repo/$client_authorized_certs.cson already contains $id.cert.pem"
+      warn "Role manifest $repo/$client/$role.txt already contains $id.cert.pem"
    else
-     headline "Adding $id.cert.pem to manifest: $repo/$client_authorized_certs.cson"
-     sed -i "s/^\]\s*$/  '${id}.cert.pem'\n\]\n/" $client_authorized_certs.cson
-     sed -i "/^$/d" $client_authorized_certs.cson
+     headline "Adding $id.cert.pem to manifest: $repo/$client/$role.txt"
+     echo ${id}.cert.pem >> $client/$role.txt
    fi
-   headline "$repo/$client_authorized_certs.cson"
-   cat $client_authorized_certs.cson
+   headline $repo/$client/$role.txt
+   cat $client/$role.txt
+   hint "OK, now try 'ghshow' to check, and 'ghcommit MESSAGE' to add all, commit and push master"
 }
 
 c0ghadd() {
    carg $# ghadd
+   role=$defaultRole
    [ ! -f $priv/latest.id ] && abort "Not found: $priv/latest.id" "Try 'gen'"
-   c1ghadd `cat $priv/latest.id`
+   c2ghadd `cat $priv/latest.id` $role
 }
 
-c2ghinit() {
-   carg $# ghinit user id
+c1ghinit() {
+   carg $# ghinit user
    user=$1
-   id=$2
-   info "ghinit user $user with cert id $2"
+   info "ghinit user $user"
    if [ -d $repo ]
    then
       abort "Already exists: $repo" "$concerto ghadd ID #or $concerto ghcommit MESSAGE"
@@ -198,62 +190,28 @@ c2ghinit() {
      abort "Invalid Github repo: $user/$repoName" \
      "Please visit https://github.com/$user and create empty repo https://github.com/$user/$repoName" \
      "Then try 'ghinit $user' again"
-   [ -f $priv/tmp/${id}.cert.pem ] || abort "Not found: $priv/tmp/${id}.cert.pem"
    mkdir $repo
    cd $repo
+   headline `pwd`
+   mkdir certs
+   mkdir $client
    headline "Initialising .git in $PWD with remote origin: git@github.com:$user/$repoName.git"
    git init
    headline "Add remote origin: git@github.com:$user/$repoName.git"
    git remote add origin git@github.com:$user/$repoName.git
    git remote -v
-   headline `pwd`
-   headline "Copying $priv/tmp/${id}.cert.pem to $repo"
-   cp -i $priv/tmp/${id}.cert.pem ${id}.cert.pem
-   openssl x509 -text -in  ${id}.cert.pem | grep 'CN='
-   ls -lta | grep -v '\.$'
-   if [ -f $client_authorized_certs.cson ]
-   then
-      if cat $client_authorized_certs.cson | grep "${id}.cert.pem"
-      then
-        warn "$client_authorized_certs.cson already contains $id.cert.pem"
-      else
-        headline "Modifying $client_authorized_certs.cson to add $id.cert.pem"
-        sed -i '/^\]\s*$/d' $client_authorized_certs.cson
-        echo -e "  '${id}.cert.pem'\n]\n" >> $client_authorized_certs.cson
-      fi
-   else
-      info "Creating $client_authorized_certs.cson with $id.cert.pem"
-      c1genm $id > $client_authorized_certs.cson
-   fi
-   headline `pwd`
-   ls -lta | grep -v '\.$'
-   echo
-   sha1sum `ls -t *.cson *.pem`
-   headline `pwd`/'$client_authorized_certs.cson'
-   cat $client_authorized_certs.cson
-   headline 'git status' `pwd`
-   git status
-   hint "OK, now try 'ghcommit MESSAGE' to add all, commit and push master"
-}
-
-c1ghinit() {
-   carg $# ghinit user
-   user=$1
-   [ -f $priv/latest.id ] || abort "Latest cert gen ID not found: $priv/latest.id"
-   id=`cat $priv/latest.id`
-   headline "ghinit $user $id"
-   c2ghinit $user $id
+   hint "OK, now try 'ghadd' to add cert to the repo"
 }
 
 c0ghinit() {
-   carg $# ghinit 
+   carg $# ghinit
    [ -f $priv/github.user ] || abort "Not found: $priv/github.user" "$concerto ghuser USER"
-   [ -f $priv/latest.id ] || abort "Latest cert gen ID not found: $priv/latest.id" "$concerto gen"
-   c2ghinit `cat $priv/github.user` `cat $priv/latest.id`
+   c1ghinit `cat $priv/github.user`
 }
 
 c1ghinitforce() {
    carg $# ghinitforce user
+   user=$1
    if [ -d $archive/$repoName ]
    then
      headline "mv $archive/$repoName $archive/`date +%Hh%Mm%S`.$repoName"
@@ -264,7 +222,7 @@ c1ghinitforce() {
      headline "mv $repo $archive/."
      mv $repo $archive/.
    fi
-   c1ghinit $1
+   c1ghinit $user
 }
 
 c1ghclone() {
@@ -317,8 +275,8 @@ c2ghcommit() {
    headline 'git remote -v'
    git remote -v
    git remote -v | grep -q "^origin\s*git@github.com:$user/$repoName.git " || abort 'git remote not git@github.com'
-   headline $repo/$client_authorized_certs.cson
-   cat $client_authorized_certs.cson
+   headline $repo/$client/manifest.json
+   cat $client/manifest.json
    headline "$repo \$ git add -A"
    git add -A
    headline "$repo \$ git commit -m '$message'"
@@ -338,8 +296,10 @@ c2ghcommit() {
    fi
    headline `pwd` 'git status'
    git status
-   headline 'Verify https://raw.githubusercontent.com/$user/$repoName/master/$client_authorized_certs.cson'
-   curl -s https://raw.githubusercontent.com/$user/$repoName/master/$client_authorized_certs.cson
+   headline "Verify https://raw.githubusercontent.com/$user/$repoName/master/$client/manifest.json"
+   curl -s https://raw.githubusercontent.com/$user/$repoName/master/$client/manifest.json
+   headline "Verify https://raw.githubusercontent.com/$user/$repoName/master/$client/$defaultRole.txt"
+   curl -s https://raw.githubusercontent.com/$user/$repoName/master/$client/$defaultRole.txt
 }
 
 c1ghcommit() {
@@ -394,29 +354,33 @@ c0ghshow() {
    fi
    if [ ! -d $repo ]
    then
-      abort "Not found: $repo" "$concerto ghinit $last #or $concerto ghclone"
+      abort "Not found: $repo" "Try 'ghinit' or 'ghclone'"
    fi
    cd $repo
    headline "$repo \$ ls"
    ls -lta | grep -v '\.$'
    headline "$repo \$ sha1sum"
-   sha1sum `ls -t *.cson *.pem`
-   if [ ! -f $client_authorized_certs.cson ]
+   sha1sum `ls -t $client/*.json certs/*.pem`
+   if [ ! -f $client/manifest.json ]
    then
-     headlinew "$repo \$ cat $client_authorized_certs.cson"
+     headlinew "$repo \$ cat $client/manifest.json"
    else
-     headline "$repo \$ cat $client_authorized_certs.cson"
-     cat $client_authorized_certs.cson
-     for cert in `cat $client_authorized_certs.cson | grep "^\s*'" | sed "s/^\s*'\([^\']*\)'/\1/"`
+     headline "$repo \$ cat $client/manifest.json"
+     cat $client/manifest.json
+     roles=$defaultRole # TODO
+     for role in $roles
      do
-        if ! echo "$cert" | grep -q '\.cert.pem$'
-        then
-           headlinew "$repo $ head $cert"
-           head -2 $cert
-        else
-          headline "$repo $ openssl x509 $cert"
-          openssl x509 -text -in $cert | grep 'CN='
-        fi
+       for cert in `cat $client/$role.txt`
+       do
+         if ! echo "$cert" | grep -q '\.cert.pem$'
+         then
+           headlinew "$repo $ head certs/$cert"
+           head -2 certs/$cert
+         else
+           headline "$repo $ openssl x509 certs/$cert"
+           openssl x509 -text -in certs/$cert | grep 'CN='
+         fi
+       done
      done
    fi
    headline "$repo \$ git remote -v"
@@ -431,13 +395,13 @@ c0ghclean() {
    headline "$repo \$ $ ls"
    ls -lta | grep -v '\.$'
    headline "$repo \$ sha1sum"
-   sha1sum `ls -t *.cson *.pem`
-   headline "$repo \$ cat $client_authorized_certs.cson"
-   cat $client_authorized_certs.cson
+   sha1sum `ls -t $client/*.json certs/*.pem`
+   headline "$repo \$ cat $client/manifest.json"
+   cat $client/manifest.json
    headline 'Check certs in repo vs manifest'
    for cert in `ls *.cert.pem`
    do
-      if ! cat $client_authorized_certs.cson | grep -q "$cert"
+      if ! cat $client/manifest.json | grep -q "$cert"
       then
          echo "Try: rm -i $repo/$cert"
       fi
@@ -454,13 +418,9 @@ c0show() {
    cd $priv/tmp
    headline "$priv/tmp $ ls -lt *.pem"
    ls -lt *.pem | head -3
-   headline "$priv/tmp $ sha1sum *.pem"
-   sha1sum `ls -t *.pem` | head -3
    cd $priv
-   headline "$priv/tmp $ ls -lt *.pem"
+   headline "$priv $ ls -lt *.pem"
    ls -lt *.pem
-   headline "$priv/tmp $ sha1sum *.pem"
-   sha1sum `ls -t *.pem` | head -3
    if [ -f cert.pem ]
    then
       headline `pwd`/cert.pem
@@ -490,11 +450,11 @@ c0help() {
    helpl "deploy ID" "copy generated cert files to $priv"
    helpl "archive" "move contents of $priv to $priv/tmp/archive"
    helpl "ghshow" "show state of $repo"
-   helpl "ghinit USER ID" "initialise $repo with generated cert"
+   helpl "ghinit USER" "initialise $repo with generated cert"
    helpl "ghclone USER" "git clone $repo"
    helpl "ghpull" "git pull $repo"
+   helpl "ghadd ID ROLE" "copy generated cert to $repo/$client/ROLE.txt"
    helpl "ghcommit MESSAGE" "git add, commit, push $repo"
-   helpl "ghadd ID" "copy generated cert to $repo"
 }
 
 c0danger1() {
